### PR TITLE
adds new logos and articles

### PR DESCRIPTION
**Pull request by kenodressel**

### CODE REVIEW

**Comment by Maurice22** [comment]
Updated with own changes, passing forward to @florianschmidt1994 for review

**Comment by florianschmidt1994** [comment]
image
I don't know what the design is on this, but could we maybe add some space between the last line "Pressekontakt" and the one before? Also maybe make the icon vertical center?

**Comment by Maurice22** [comment]
This should not look like this tbh. have you pulled the most recent version?

**Comment by florianschmidt1994** [comment]
Now I do :) LGTM

**Pull request merged**
