### PR TITLE
Make base URL configurable for local dev

### PR DESCRIPTION
**Pull request by timjb**
This makes it possible to test authentication locally when developping on
localhost:3000 by replacing `src/appConfig.jsx` with
`src/appConfig.dev.jsx`.

### CODE REVIEW

**Comment by kenodressel** [comment]
Could we use ENV variables to automatically switch between the environments?

**Comment by timjb** [comment]
@kenodressel Good idea, I will try this out!

**Comment by timjb** [comment]
@kenodressel It worked, please have another look at this PR :-)

We could use the same mechanism to make it more easier to

* use another firebase configuration and to
* set feature flags

during development. If you agree, I would start working on that after this PR is merged.

**Comment by kenodressel** [comment]
Yes I think its a good idea but we should be careful to always include all env varibales in the repo.

**Pull request merged**
