### PR TITLE
Added share buttons

### PR DESCRIPTION
**Pull request by yorickreum**
I added share buttons for Email, Facebook, Telegram, Twitter, WhatsApp.

### CODE REVIEW

**Comment by yorickreum** [comment]
Yes, I just encountered this too, the problem is that the buttons are underneath the header… Will fix this asap. In the sidebar they should work fine. Is the position okay like this?

**Comment by yorickreum** [comment]
Fixed it. Also added a custom "copy to clipboard" button. The buttons in the sidebar now wrap into two rows.

**Comment by thepiwo** [comment]
@yorickreum could you please either rebase the changes from master, or I'll have rebase and push to master manually, as github can't resolve the conflicts here.

**Comment by thepiwo** [comment]
the `yarn.lock` was deleted in master, this seems to be an issue here, sorry for the inconvenience

**Comment by yorickreum** [comment]
No problem… Thanks for your work. Maybe just delete and regenerate yarn.lock?

**Comment by thepiwo** [comment]
I rebased and resolved the issues here: https://github.com/kenodressel/quarantine-hero/pull/10

Closing this PR, I hope this is ok for you @yorickreum

**Pull request closed without merging**
