### PR TITLE
List responses to requests for help on dashboard

### LINKED ISSUE #52: List responses on dashboard
To be discussed but we get requests from people who are unable to receive their responses.

### PR DESCRIPTION
**Pull request by timjb**
This fixes #52 at least partially. Additionally, changes to the security rules may be required, but I can't tell for sure because I don't have access to them.

Screenshots:

on desktop
on mobile

### CODE REVIEW

**Comment by florianschmidt1994** [comment]
Hi @timjb, thanks for working on this! Let me pass your concept to our designer and I'll make sure to give you his feedback ASAP. :) Generally I'm really happy with the idea and think we're going in a good direction with this!

**Comment by florianschmidt1994** [comment]
Based on your idea this is the feedback I've gotten from our designer. I hope this helps :) 

**Mobile**
messenger

**Comment by timjb** [comment]
@florianschmidt1994 I've implemented the new design.

Here's a video of me testing this feature: https://drive.google.com/file/d/18V-6kKITp6LxaEijhH56rMz1VKv5mwwA/view

**Comment by florianschmidt1994** [comment]
Hi @timjb. Just a quick update, I'm waiting for a good solution for a staging environment to exist in order to give this a proper testing :) It looks really really good, I hope it's ok to keep you waiting with merging this for a little longer.

**Comment by florianschmidt1994** [comment]
Could you rebase this on the current `develop` branch and resolve the conflicts? It now also includes the setup for the staging firebase config, so we could test it right away :)

**Comment by timjb** [comment]
@florianschmidt1994 Sure!

**Comment by timjb** [comment]
@florianschmidt1994 I've rebased this PR onto the current HEAD of `development`.

**Comment by timjb** [comment]
@florianschmidt1994 @yorickreum Please have a look at this PR and at [this page](https://www.i18next.com/translation-function/plurals) to learn how to do pluralization using i18next.

**Comment by florianschmidt1994** [comment]
Looks good so far. I'll get together with @kenodressel to discuss how we have to modify our security rules in firebase in order to make this work in prod and let you know once we've come up with a plan.

**Comment by Maurice22** [comment]
@florianschmidt1994 @kenodressel
As this PR is changing the behavior of the Entry component anyways, wouldn't it make sense to disable the onclick redirect if the entry is displayed in the user's overview. Because certainly, the creator of the Entry will not offer help for his own issue.

**Comment by timjb** [comment]
I won't have time to work on this PR before tomorrow evening. If you want something changed, you have to either wait until then or do it yourself.

**Comment by florianschmidt1994** [comment]
@Maurice22 I agree with your assessment that this behaviour does not make much sense, but I think it's out of scope for this PR. Can you please open an issue?

**Comment by Maurice22** [comment]
Created #129

**Pull request merged**
